
" reset everything to the Vim defaults
" this ensures consistency between platforms
set nocompatible all&

if &term != "linux"
    let airline_powerline_fonts=1
endif

let g:airline#extensions#tabline#show_buffers=0
let g:airline#extensions#tabline#tab_min_count=2
let g:airline#extensions#tabline#formatter = 'unique_tail_improved'
let g:airline#extensions#tabline#enabled=1

" don't show the intro message on startup
set shortmess+=I

" use UTF-8 for new files
setglobal fileencoding=utf-8

" prefer UNIX line endings, even on Windows
set fileformats=unix,dos
setglobal fileformat=unix

" keep buffers open even when they're not visible
set hidden

" indent to a stop of four spaces
set softtabstop=4 tabstop=4 shiftwidth=4

" use soft tabs by default
set expandtab

" use the clipboard register for all unnamed register actions
set clipboard+=unnamed

" allow mouse usage in all modes
set mouse=a

" focus follows mouse, as $deity intended
set mousefocus

" use <Tab> completion similar to bash
" insert the longest common prefix on first activation
" on second activation list all possible completions
set wildmode=longest,list:longest

set number numberwidth=4

if has("gui_running")
    " use Airline's tab bar in favor of the GUI widget
    set guioptions-=e

    " disable the menu and tool bars
    set guioptions-=m guioptions-=T guioptions+=M

    " turn off all the scrollbars
    set guioptions-=l guioptions-=L " left
    set guioptions-=r guioptions-=R " right
    set guioptions-=b               " bottom

    if has("gui_gtk")
        set guifont=Droid_Sans_Mono_Dotted_for_Powerline_9
    elseif has("gui_win32")
        set guifont=Droid_Sans_Mono_Dotted_for_Powe:h10
    endif
endif

syntax enable

if &term != "linux"
    " use Solarized Dark colors
    set background=dark

    " force Solarized.vim to use the default terminal background
    " color for base03 instead of brtblack as that's remapped to base01
    let g:solarized_termtrans=1
    colorscheme solarized
endif


" style the :sign gutter identically to the 'number' gutter
highlight clear SignColumn
highlight link SignColumn LineNr


""" Syntastic

" run in passive mode by default for all files
" this may be overridden per buffer by ftplugins
let g:syntastic_mode_map = {'mode': 'passive'}

" run checks when a file is first opened
"let g:syntastic_check_on_open = 1

" do not run checks when exiting Vim
let g:syntastic_check_on_wq = 0


" don't show baloons on hover in gVim
let g:syntastic_enable_balloons = 0


highlight SyntasticErrorSign term=bold cterm=bold ctermfg=1 ctermbg=0
highlight SyntasticWarningSign term=bold cterm=bold ctermfg=5 ctermbg=0
