
" reset everything to the Vim defaults
" it's the Vim defaults because this is a vimrc file
set all&

" set up the Pathogen runtime path mangling system
runtime bundle/pathogen/autoload/pathogen.vim
execute pathogen#infect()

" use Solarized Dark colors
syntax enable
set background=dark
colorscheme solarized
