
" reset everything to the Vim defaults
" this ensures consistency between platforms
set nocompatible all&

" set up the Pathogen runtime path mangling system
runtime bundle/pathogen/autoload/pathogen.vim
execute pathogen#infect()

" don't show the intro message on startup
set shortmess+=I

" use UTF-8 for new files
set fileencoding=utf-8

" prefer UNIX line endings, even on Windows
set fileformat=unix fileformats=unix,dos

" keep buffers open even when they're not visible
set hidden

" indent to a stop of four spaces
set softtabstop=4 tabstop=4 shiftwidth=4

" use soft tabs by default
set expandtab

" use the clipboard register for all unnamed register actions
" don't connect to X from command-line Vim
set clipboard=unnamed,exclude:.*

" allow mouse usage in all modes
set mouse=a

" focus follows mouse, as $deity intended
set mousefocus

set number numberwidth=4

if has( "gui_running" )
    " use the native tab widget
    set guioptions+=e

    " disable the menu and tool bars
    set guioptions-=m guioptions-=T guioptions+=M

    " turn off all the scrollbars
    set guioptions-=l guioptions-=L " left
    set guioptions-=r guioptions-=R " right
    set guioptions-=b               " bottom

    if has("gui_gtk")
        set guifont='DejaVu Sans Mono 10'
    endif
endif

" use Solarized Dark colors
syntax enable
set background=dark
colorscheme solarized
